services:
  redis-svc:
    image: redis
    ports:
      - 6379
  livekit:
    image: livekit/livekit-server
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - 7880:7880
    volumes:
      - ./livekit-server.yaml:/etc/livekit.yaml
  livekit-egress:
    image: livekit/egress
    environment:
      - EGRESS_CONFIG_FILE=/out/config.yaml
    volumes:
      - ./livekit-egress/config.yaml:/out/config.yaml